---
title: "Assignment 2"
author: "Adam Qian"
date: "May 12, 2017"
output: html_document
---

```{r Import and Tidy, eval=TRUE, echo=TRUE, warning=FALSE}
CAFeaturesData = read.delim("D:/Yifu Qian's love/UCSB Learning/2016 -2017 Spring Quarter/Environmental Informatics/Assignment 2/CA_Features_20170401.txt", sep = "|",header = TRUE)

CAData1 = subset(CAFeaturesData,select = -c(STATE_NUMERIC,COUNTY_NUMERIC,PRIMARY_LAT_DMS,PRIM_LONG_DMS,SOURCE_LAT_DMS,SOURCE_LONG_DMS,ELEV_IN_FT))


colnames(CAData1) = c("ID","Name","FeatureClass","State","County","Latitude","Longitude","SourceLatitude", "SourceLongitude", "Elevation","MapName","DateCreate","DateEdit")

CAData2<-subset(CAData1,CAData1$State=="CA")
CAData3<-subset(CAData2,CAData2$Latitude>0)
CaliforniaFinal<-subset(CAData3,CAData3$Longitude<0)
write.table(CaliforniaFinal,"CaliforniaFinal.csv",sep = "|")
```

```{r Analyze, eval=TRUE, echo=TRUE, warning=FALSE}
library(tidyverse)
#The most-frequently-occuring feature name

MaxName<- group_by(CaliforniaFinal,Name)
MaxName1<-summarise(MaxName,count=n())
Max=which.max(MaxName1$count)
MaxName1[Max,c("Name","count")]


#The least-frequently-occuring feature class

LeastClass<- group_by(CaliforniaFinal,FeatureClass)
LeastClass1<-summarise(LeastClass,count=n())
Min=which.min(LeastClass1$count)
LeastClass1[Min,c("FeatureClass","count")]

# Center of each county
Center<-group_by(CaliforniaFinal, County)
CenterLat<-summarise(Center,MeanLat=mean(Latitude,na.rm=TRUE))
CenterLong<-summarise(Center,MeanLong=mean(Longitude,na.rm=TRUE))
Centerpoint<-left_join(CenterLat,CenterLong,by="County")


#The fraction of the total number features in each county by manmade and nature

#create new cloumn
FeatureClass = c("Airport","Arch","Area","Arroyo","Bar","Basin","Bay","Beach","Bench","Bend","Bridge","Building","Canal","Cape","Cave","Cemetery","Census","Channel","Church","Civil","Cliff","Crater","Crossing","Dam","Falls","Flat","Forest","Gap","Glacier","Gut","Habor","Hospital","Island","Isthmus","Lake","Lava","Levee","Locale","Military","Mine","Oifield","Park","Pilar","Plain","PopulatedPlace","PostOffice","Range","Rapids","Reserve","Reservoir","Ridge","School","Sea","Slope","Spring","Stream","Summit","Swamp","Tower","Trail","Tunnel","Unknown","Valley","Well","Woods")

#Manmade=m,Natural=n
Definition = c("m","n","n","n","n","n","n","n","n","n","m","m","m","n","n","m","m","n","m","m","n","n","m","m","m","n","n","n","n","n","m","m","n","n","n","n","m","m","m","n","n","m","m","n","m","m","n","n","m","m","n","m","n","n","n","n","n","n","m","m","m","NA","n","m","n")
Defi = data.frame(FeatureClass,Definition)


Defi1 = select(CaliforniaFinal,c(County,FeatureClass))

Defi2 = inner_join(Defi1,Defi,by="FeatureClass")
Nature<-subset(Defi2,Defi2$Definition=="n")
Nature1<-group_by(Nature,County)
Nature2<-summarise(Nature1,count=n())

Manmade<-subset(Defi2,Defi2$Definition=="m")
Manmade1<-group_by(Manmade,County)
Manmade2<-summarise(Manmade1,count=n())
Fraction<-left_join(Nature2,Manmade2,by="County")
colnames(Fraction)[2]<-"Natural"
colnames(Fraction)[3]<-"Man-made"
Fraction$FractionNatural<-Fraction$Natural/(Fraction$Natural+Fraction$`Man-made`)
Fraction$FractionManmade<-Fraction$`Man-made`/(Fraction$Natural+Fraction$`Man-made`)
```

